### ISSUE TITLE
Truncated File Issue After Generating Flanking Seqs Step

### ISSUE THREAD

**Issue by kellybarr** [KrisChristensen/MapVCF2NewGenome#1]
Any clue why this might be happening?  I'm running VCF_2_Fasta_v1.1.py with no reported errors.  But the mapping step keeps kicking out this "truncated file" error.  Like this:  

[M::mem_process_seqs] Processed 49752 reads in 10.999 CPU sec, 10.926 real sec
[M::process] read 49752 sequences (10000152 bp)...
[M::mem_process_seqs] Processed 49752 reads in 11.168 CPU sec, 11.104 real sec
[E::sam_parse1] query name too long
[W::sam_read1_sam] Parse error at line 987047
samtools sort: truncated file. Aborting

**Comment by KrisChristensen** [comment]
It looks like samtools encounters a query name that is too long.  I'm guessing this error might cause the file to be truncated.  It might be informative to look through the fasta headers to see if there is an oddity.  It looks like earlier SNPs names were processed OK though.

I'm wondering if these are biallelic SNPs or not.  If they are not, this script won't work for your case.  There might be some instances where the alternative allele is a long string of nucleotides and perhaps that is why you are getting a query header issue.

**Comment by KrisChristensen** [comment]
If you are able to upload an example fasta file, I will investigate.

**Comment by kellybarr** [comment]
That's it.  I didn't remove indels.  I'm rerunning it now sans indels.  I thought I had removed them by restricting variants to only two; but it turns out you can still get indels with that.

**Comment by KrisChristensen** [comment]
Excellent!  Good luck!
