### ISSUE TITLE
error while running the CheckMappingVCF.v1.0.py

### ISSUE THREAD

**Issue by angi-bvg** [KrisChristensen/MapVCF2NewGenome#2]
Hi, I am having problems generating the old2new.positions_filtered.txt

Everything ran correctly until step 5 (below), but then I got this error regarding the location of a key "KeyError: 'CAE02294'", but old2new.positions.txt contains the mentioned key. Any idea of what it can be?

Is it possible to add some dummy data so that I can test the different steps?
I have tried with other data sets without success either.

I am attaching the files here too. 
[Test.zip](https://github.com/KrisChristensen/MapVCF2NewGenome/files/13501024/Test.zip)

Thanks for your help.

python CheckMappingVCF.v1.0.py -map old2new.positions.txt -fasta1 flankingSeqs.fasta -fai1 flankingSeqs.fasta.fai -fasta2 newGenome.fasta -fai2 newGenome.fasta.fai -flanking 20 -output most > old2new.positions.filtered.txt

Running CheckMappingVCF version: 1.0 with the following parameters:
        -map: old2new.positions.txt
        -fasta1: flankingSeqs.fasta
        -fasta2: newGenome.fasta
        -fai1: flankingSeqs.fasta.fai
        -fai2: newGenome.fasta.fai
        -flanking: 20
        -output: most
        -verbose: NA

Opened index of fasta file (fai1): flankingSeqs.fasta.fai
        Finished reading scaffold fasta fai file: Found 37 sequence(s)
        Total Nucleotide(s): 7437

Opened index of fasta file (fai2): newGenome.fasta.fai
        Finished reading scaffold fasta fai file: Found 1115 sequence(s)
        Total Nucleotide(s): 1863494

Opened map file: old2new.positions.txt
Traceback (most recent call last):
  File "/env/export/cns_n02_proj/proj21/q_seq_lab/Angelina/M2/SOIL/Genetic_Variability/VCF/MapVCF2NewGenome-main/Test/CheckMappingVCF.v1.0.py", line 202, in <module>
    open_map = OpenFile(args.map, "map", "1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/export/cns_n02_proj/proj21/q_seq_lab/Angelina/M2/SOIL/Genetic_Variability/VCF/MapVCF2NewGenome-main/Test/CheckMappingVCF.v1.0.py", line 38, in __init__
    self.readLinesMap(self.file)
  File "/env/export/cns_n02_proj/proj21/q_seq_lab/Angelina/M2/SOIL/Genetic_Variability/VCF/MapVCF2NewGenome-main/Test/CheckMappingVCF.v1.0.py", line 72, in readLinesMap
    if ((int(self.start1) > 0 and int(Variables.sequences1[self.contig1]) >= int(self.end1)) and
                                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'CAE02294'

**Comment by KrisChristensen** [comment]
Hello,

I modified the CheckMappingVCF.v1.0.py script, it should work with your data now.  The problem was with how the script handled underscore characters.  You'll just have to download the new script and replace the old.  Good luck with your research!

Kris Christensen
